<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>Setup.Core.Tests</AssemblyName>
    <PathMap>$(MSBuildProjectDirectory)=/_/MalumMenuEnhanced/tests/Setup.Core.Tests</PathMap>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../installer/MalumMenuEnhanced.Setup.Core/MalumMenuEnhanced.Setup.Core.csproj" />
  </ItemGroup>
</Project>
